config/routes.rb
Spinworkouts::Application.routes.draw do

  resources :workouts do
	resources :comments
  end

  root :to => "home#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :workout
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :workout
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  validates :name, :presence => true,
					:length => { :minimum => 4 }
  has_many :comments, :dependent => :destroy
  has_many :tags

  accepts_nested_attributes_for :tags, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k,v| v.blank? } }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from User::NotAuthorized, :with => :user_not_authorized
  protect_from_forgery

  private

  def authenticate
    authenticate_or_request_with_http_basic do |user_name, password|
      user_name == 'admin' && password == 'password'
    end
  end

  def user_not_authorized
    flash[:error] = "You don't have access to this section."
    redirect_to :back
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate, :only => :destroy

  def create
    @workout = Workout.find(params[:workout_id])
    @comment = @workout.comments.create(params[:comment])
    redirect_to workout_path(@workout)
  end

  def destroy
    @workout = Workout.find(params[:workout_id])
    @comment = @workout.comments.find(params[:id])
    @comment.destroy
    redirect_to workout_path(@workout)
  end
 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  # GET /workouts
  # GET /workouts.xml
  def index
    @workouts = Workout.all

    respond_to do |format|
      format.html # index.html.erb
      # format.xml  { render :xml => @workouts }
      format.xml  # index.xml.builder
      # format.xml { send_file("#{Rails.root}/app/controllers/allWorkouts.xml",
      #	 { :type => "application/xml" }) }
    end
  end

  # GET /workouts/1
  # GET /workouts/1.xml
  def show
    @workout = Workout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      #format.xml  { render :xml => @workout.to_xml(:include => [:tags, :comments]) }
      format.xml  # show.xml.builder
    end
  end

  # GET /workouts/new
  # GET /workouts/new.xml
  def new
    @workout = Workout.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @workout }
    end
  end

  # GET /workouts/1/edit
  def edit
    @workout = Workout.find(params[:id])
  end

  # POST /workouts
  # POST /workouts.xml
  def create
    @workout = Workout.new(params[:workout])

    respond_to do |format|
      if @workout.save
        format.html { redirect_to(@workout, :notice => 'Workout was successfully created.') }
        format.xml  { render :xml => @workout, :status => :created, :location => @workout }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @workout.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /workouts/1
  # PUT /workouts/1.xml
  def update
    @workout = Workout.find(params[:id])

    respond_to do |format|
      if @workout.update_attributes(params[:workout])
        format.html { redirect_to(@workout, :notice => 'Workout was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @workout.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.xml
  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy

    respond_to do |format|
      format.html { redirect_to(workouts_url) }
      format.xml  { head :ok }
    end
  end

  private

  def record_not_found
    render :text => "404 Not Found", :content_type => "text/html", :status => 404
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
  def join_tags(workout)
    workout.tags.map { |t| t.name }.join(", ")
  end
end

app/views/comments/_comment.html.erb
<p>
  <b>Commenter:</b>
  <%= comment.commenter %>
</p>
 
<p>
  <b>Comment:</b>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.workout, comment],
               :confirm => 'Are you sure?',
               :method => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@workout, @workout.comments.build]) do |f| %>
  <div class="field">
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spinworkouts</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
<script type="text/javascript">
//<![CDATA[
var FLASH_MINREV = "9.0.115";
var FLASH_GOODREV = "9.0.115";

/*
var player_default_flashvars =
    {"api_baseurl":"<?php echo Yii::getPathOfAlias('url_api')?>",
    "baseurl":"<?php echo Yii::getPathOfAlias('url_base')?>",
    "bgcolor":"#ffffff",
    "is_enablejs":true,
    "is_onsite":true,
    "javascript_id":"swsWorkoutPlayer",
    "loader_name":"",
    "parent_div":"workoutPlayerPanel",
    "player_baseurl":"<?php echo Yii::getPathOfAlias('url_player')?>",
    "player_name":"WorkoutApp",
    "so_path":"sws-so1",
    "use_loader":false,
    "user_id":"<?php if (isset(Yii::app()->user->id)) echo Yii::app()->user->id; else echo '0';?>"
    };
var player_load_object = {};
<?php
if (isset(Yii::app()->user->id)) {
    Yii::import('application.modules.user.models.User');
    echo "SWS.user.uid = " . Yii::app()->user->id . ";\n";
    $user = User::model()->findByPk(Yii::app()->user->id);

    if ($user && $user->hasComplied) {
        echo "SWS.user.hasComplied = 1;\n";
    } 
}
?>
*/

//]]>
</script>
</head>
<body style="background: #EEEEEE">
<div id="wrapper">
	<div id="page">
		<%= render :partial => 'nav/top' %>
		<%# render :partial => 'nav/top', :locals => { :top => @nav } #%>
	    <div id="container">
	        <div id="content" class="twothirds columns">
	            <div id="main-wrapper">
	                <div id="main-search" class="twothirds columns">
                            <br>
	                    <h3>Welcome to Spinworkouts, a tool for indoor cycling workouts.</h3>
	                    <br><br>
                            <h3>Checkout our featured workouts:</h3>
                        </div>
	                <div id="flex-wrapper" class="WORKOUT_TEASER twothirds columns">
	                    <div id="workoutPlayerPanel"></div>
	                </div>

<!--
	                    <form id="frmGlobalSearch" action="http://steve.dev.he.playlist.com/searchbeta" method="get">
	                        <input id="txtGlobalSearch" type="text" name="searchfor" class="textbox idleField" maxlength="100" value="Search for a song or artist"/>
	                        <input id="globalSearchType" type="hidden" name="t" value="tracks"/>
	                        <button type="submit" class="image_button" id="nav_search_button">Search</button>
	                        <div id="search_facets"> </div>
	                    </form>
-->
	            </div>
	            <div id="html-wrapper"> 
<%= yield %>
	            </div>
	        </div><!-- content -->
	        <div id="right-column" class="third column last">
	            <iframe height="250" width="300" style="margin-right: 0;"></iframe>
	        </div>
	        <div id="debug" class="third column last">
	            <textarea id="debug-txt" style="width:300px;height:400px;border:0px;"></textarea>
	        </div>
	    </div><!-- container -->
	    <div id="footer">
	        Copyright &copy; 2011 by Strategic Workout Systems LLC.<br/>
	        All Rights Reserved.<br/>
	    </div><!-- footer -->
	</div><!-- page -->
</div><!-- wrapper -->
<script type="text/javascript"> 
//<![CDATA[ 
    //SWS.init();
//]]> 
</script>

</body>
</html>

app/views/nav/_top.html.erb
		<div id="nav">
	        <h6><a href="/" class="ajax">Spinworkouts<!--<?php echo CHtml::encode(Yii::app()->name); ?>--></a></h6>
                    <div id="nav-user">
<!--
	            	<?php $this->renderPartial("application.views.nav.top");?>
-->

						<ul id="nav-user-links">
							<li><a href="/site/contact" class="ajax modal">Contact</a></li>
<!--
<?php 
/*  TODO: profile editting
if (!Yii::app()->user->isGuest) {
    echo '<li><a href="/user/profile" class="ajax modal">Profile</a></li>';
}
*/
?>
-->
						</ul>
						<p>
<!--
<?php 

if (Yii::app()->user->isGuest) { 
    echo '<a href="/user/login" class="ajax modal">Login</a>';
    echo '<span> | </span>';
    echo '<a href="/user/registration" class="ajax modal">Sign Up</a>';
} else {
    echo '<a href="/user/profile">Hi, '.Yii::app()->user->getName().'</a>';
    echo '<span> | </span>';
    echo '<a href="/user/logout" class="ajax">Logout</a>';
}
?>
-->
						</p>


                    </div>
		</div><!-- nav -->

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
  <div class="field">
    <%= tag_form.label :name, 'Tag:' %>
    <%= tag_form.text_field :name %>
  </div>
  <% unless tag_form.object.nil? || tag_form.object.new_record? %>
    <div class="field">
      <%= tag_form.label :_destroy, 'Remove:' %>
      <%= tag_form.check_box :_destroy %>
    </div>
  <% end %>
<% end %>

app/views/workouts/_form.html.erb
<% @workout.tags.build %>
<%= form_for(@workout) do |workout_form| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= workout_form.label :name %><br />
    <%= workout_form.text_field :name %>
  </div>
  <div class="field">
    <%= workout_form.label :description %><br />
    <%= workout_form.text_field :description %>
  </div>
  <div class="field">
    <%= workout_form.label :duration %><br />
    <%= workout_form.text_field :duration %>
  </div>
  <h2>Tags</h2>
  <%= render :partial => 'tags/form',
             :locals => {:form => workout_form} %>
  <div class="actions">
    <%= workout_form.submit %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render 'form' %>

<%= link_to 'Show', @workout %> |
<%= link_to 'Back', workouts_path %>

app/views/workouts/index.html.erb
<h1>Listing workouts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Duration</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @workouts.each do |workout| %>
  <tr>
    <td><%= workout.name %></td>
    <td><%= workout.description %></td>
    <td><%= workout.duration %></td>
    <td><%= link_to 'Show', workout %></td>
    <td><%= link_to 'Edit', edit_workout_path(workout) %></td>
    <td><%= link_to 'Destroy', workout, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Workout', new_workout_path %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render 'form' %>

<%= link_to 'Back', workouts_path %>

app/views/workouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @workout.name %>
</p>

<p>
  <b>Description:</b>
  <%= @workout.description %>
</p>

<p>
  <b>Duration:</b>
  <%= @workout.duration %>
</p>

<p>
  <b>Tags:</b>
  <%= join_tags(@workout) %>
</p>

<h2>Comments</h2>
<%= render :partial => "comments/comment",
           :collection => @workout.comments %>


<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Edit Workout', edit_workout_path(@workout) %> |
<%= link_to 'Back to Workouts', workouts_path %>